/**
 * MedicalDisclaimer Component
 * Persistent footer disclaimer for medical advice
 */

import React from 'react';
import { AlertTriangle } from 'lucide-react';

/**
 * MedicalDisclaimer - Shows a persistent medical disclaimer
 * @param {boolean} compact - Whether to show compact version
 * @param {string} className - Additional CSS classes
 */
const MedicalDisclaimer = ({ compact = false, className = '' }) => {
    if (compact) {
        return (
            <div className={`text-xs text-stone-400 text-center py-2 px-4 ${className}`}>
                <span className="font-medium">Medical Disclaimer:</span> This app is for tracking purposes only.
                Always consult your doctor.
            </div>
        );
    }

    return (
        <div className={`bg-amber-50 border border-amber-200 rounded-xl p-4 ${className}`}>
            <div className="flex items-start gap-3">
                <AlertTriangle className="text-amber-500 flex-shrink-0 mt-0.5" size={20} />
                <div>
                    <h4 className="font-bold text-amber-800 text-sm mb-1">
                        Medical Disclaimer
                    </h4>
                    <p className="text-amber-700 text-sm leading-relaxed">
                        This application is intended for personal health tracking only.
                        It does not provide medical advice, diagnosis, or treatment recommendations.
                        Always consult with your healthcare provider before making any changes to your
                        diabetes management plan.
                    </p>
                </div>
            </div>
        </div>
    );
};

/**
 * AIInsightDisclaimer - Specific disclaimer for AI-generated content
 */
export const AIInsightDisclaimer = ({ className = '' }) => {
    return (
        <div className={`bg-blue-50 border border-blue-200 rounded-xl p-3 ${className}`}>
            <div className="flex items-start gap-2">
                <AlertTriangle className="text-blue-500 flex-shrink-0 mt-0.5" size={16} />
                <div>
                    <h4 className="font-bold text-blue-800 text-xs mb-0.5">
                        AI Advisory Notice
                    </h4>
                    <p className="text-blue-700 text-xs leading-relaxed">
                        This insight is generated by AI for informational purposes only.
                        It is not a substitute for professional medical advice. Confidence levels
                        indicate the AI's certainty, not medical accuracy.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default MedicalDisclaimer;
